"""Frozen 225RaF A(0)-X(0) hyperfine numbers for the level diagram.

AUTO-GENERATED by compute_225_xa_branching.py (PHYSICAL/canonical params).
Do not hand-edit; re-run the compute script.

PROVENANCE: RaF225 X-A.ipynb cells 26-31, A-state with dYb -> -dYb = -0.076*c
(225Ra mu_I<0, opposite 171Yb; the +0.076*c default is a borrowed "Wilkins"
171Yb placeholder) and the REAL Skripnikov h1/2Yb=-1426 (NOT the scratch h1/2=0).
Canonical per Arian 2026-06-05. branching_ratios(X0,A0,0,1e-8), M=none.
NB: branching is INSENSITIVE to the A hyperfine params (default==exp==phys to
4 sig figs); only the A-state energies depend on this choice.
All energies MHz, relative to the lowest level of their manifold group.
Branching = conditional on decay to v''=0 (hyperfine fraction only).
"""

CYCLING_UPPER_BR_SUM = 1.0  # column closure check

# A 2Pi_1/2 (v=0) J=1/2 parity+ levels: list of (F1, F, E_rel_MHz)
A_LEVELS = [
    (1, 0.5, 0.0),
    (1, 1.5, 4.9093986),
    (0, 0.5, 2456.07893414),
]

# X 2Sigma (v=0) N=1 levels: list of (G, F1, F, E_rel_MHz)
X_N1_LEVELS = [
    (1, 1, 0.5, 0.0),
    (1, 1, 1.5, 39.97920676),
    (1, 0, 0.5, 316.65371587),
    (1, 2, 1.5, 320.74782082),
    (1, 2, 2.5, 378.03247631),
    (0, 1, 1.5, 16813.32147035),
    (0, 1, 0.5, 16814.09501663),
]

# Branching from cycling upper state (A J=1/2+ F1=0), grouped by ground
# (N, G, F1), summed over F. Conditional on v''=0.
BRANCHING_BY_F1 = {
    (1, 1, 1): 0.9899580445427187,
    (1, 1, 2): 0.005853570168756713,
    (1, 1, 0): 0.004131236597855839,
    (1, 0, 1): 5.714390429952246e-05,
    (3, 1, 2): 8.6184599710759e-11,
    (0, 1, 1): 1.0535833907068512e-34,
    (2, 1, 1): 7.608685437254845e-35,
    (2, 1, 2): 1.6286491391146372e-35,
    (0, 0, 0): 4.7618144648554575e-40,
    (2, 0, 2): 7.735352716847721e-41,
    (2, 1, 3): 0.0,
    (3, 1, 3): 0.0,
    (3, 1, 4): 0.0,
    (3, 0, 3): 0.0,
}

